INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") 
VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3OISupportStrengthSpikeAversion-baseDelta0.5-premiumSpikePercent8-topOIs5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3OISupportStrengthSpikeAversionAlgoThread', NULL, 700);

INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'topOIs', 'int', '5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');



INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3StraddleToStrangleSpikeAversion-startingDelta0.25-premiumSpikePercent8-deltaUpgradeStep0.05-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3StraddleToStrangleSpikeAversionAlgoThread', NULL, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'startingDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'deltaUpgradeStep', 'float', '0.05');


INSERT INTO db_versions VALUES('0012', now(), 'Keshav', 'OI Support strength based Algo','Data' );