INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "hedge_distance", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "max_hedge_cost_per_leg", "non_directional") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3SpikeManagedBuyAndAutoIndexFollower-baseDelta0.5-premiumSpikePercent8-indexPoints50-noLimit', '09:20:00', '15:15:00', 1, 500, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeManagedBuyAndAutoIndexFollowerAlgoThread', NULL, '1.5', 't');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'indexPoints', 'float', '25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "hedge_distance", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "max_hedge_cost_per_leg", "non_directional") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3AutoIndexFollowerRollingSpikeAversion-baseDelta0.5-premiumSpikePercent8-indexPoints25-noLimit', '09:20:00', '15:15:00', 1, 500, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3AutoIndexFollowerRollingSpikeAversionAlgoThread', NULL, '1.5', 't');

INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'indexPoints', 'float', '50');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');

INSERT INTO db_versions VALUES('0016', now(), 'Keshav', 'Spike Aversion buy and mix algo','Data' );