ALTER TABLE nexcorio_option_atm_movement_data 
ADD COLUMN outlierCEMinIV REAL DEFAULT 0,
ADD COLUMN outlierPEMinIV REAL DEFAULT 0,
ADD COLUMN outlierCEMaxIV REAL DEFAULT 0,
ADD COLUMN outlierPEMaxIV REAL DEFAULT 0,
ADD COLUMN outlierCETotalIV REAL DEFAULT 0,
ADD COLUMN outlierPETotalIV REAL DEFAULT 0,
ADD COLUMN outlierCEAvgIV REAL DEFAULT 0,
ADD COLUMN outlierPEAvgIV REAL DEFAULT 0,
ADD COLUMN outlierCEMedianIV REAL DEFAULT 0,
ADD COLUMN outlierPEMedianIV REAL DEFAULT 0;

INSERT INTO db_versions VALUES ('0036', now(), 'Keshav', 'Additional column for ATM data', 'Schema');