INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3SpikeAversionStrangleAlgoThread-greekDelta-baseDelta0.25-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', NULL, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'delta');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3GreekParityPremiumSpikeAversion-greekIV-baseDelta0.5-premiumSpikePercent8-ivDiffCutoffPercent5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekParityPremiumSpikeAversionAlgoThread', NULL, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'ivDiffCutoffPercent', 'float', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3DualIVParityAndOIWorthStraddle-baseDelta0.5-ivDiffCutoffPercent5-filterOptionWorth-topOis5-noLimit', '09:20:45', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3DualIVParityAndOIWorthStraddleAlgoThread', NULL, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'ivDiffCutoffPercent', 'float', '5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'filterOptionWorth', 'boolean', 'TRUE');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'topOis', 'int', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3GreekParity-greekIV-baseDelta0.5-greekDiffCutoffPercent5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekParityAlgoThread', NULL, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekDiffCutoffPercent', 'float', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 4, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3GreekGap-greekGamma-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 31, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'gamma');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3SpikeAversionStrangleAlgoThread-greekVega-baseDelta0.25-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 1, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'vega');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3SpikeAversionStrangleAlgoThread-greekVega-baseDelta0.5-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 39, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'vega');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3SpikeAversionStrangleAlgoThread-greekDelta-baseDelta0.5-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 1, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'delta');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3SpikeAversionStrangleAlgoThread-greekDelta-baseDelta0.25-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 1, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'delta');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3GreekParity-greekIV-baseDelta0.5-greekDiffCutoffPercent5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekParityAlgoThread', 4, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekDiffCutoffPercent', 'float', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 31, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3GreekGap-greekGamma-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 33, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'gamma');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3SpikeAversionStrangleAlgoThread-greekVega-baseDelta0.25-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 39, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'vega');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3SpikeAversionStrangleAlgoThread-greekVega-baseDelta0.5-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 40, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'vega');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3SpikeAversionStrangleAlgoThread-greekDelta-baseDelta0.5-premiumSpikePercent8-acceptableDiff0.2-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3SpikeAversionStrangleAlgoThread', 42, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'delta');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumDiff', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'acceptableDiff', 'float', '0.2');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'rollingPoints', 'float', '0');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3GreekGap-greekIV-baseDelta0.6-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 31, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.6');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3StraddleToStrangleSpikeAversion-startingDelta0.25-premiumSpikePercent8-deltaUpgradeStep0.05-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3StraddleToStrangleSpikeAversionAlgoThread', 1, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'startingDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'deltaUpgradeStep', 'float', '0.05');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3StraddleToStrangleSpikeAversion-startingDelta0.25-premiumSpikePercent8-deltaUpgradeStep0.05-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3StraddleToStrangleSpikeAversionAlgoThread', 51, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'premiumSpikePercent', 'float', '8');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'startingDelta', 'float', '0.25');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'deltaUpgradeStep', 'float', '0.05');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 6, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 31, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 4, 'G3DualIVParityAndOIWorthStraddle-baseDelta0.5-ivDiffCutoffPercent5-filterOptionWorth-topOis5-noLimit', '09:20:45', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3DualIVParityAndOIWorthStraddleAlgoThread', 3, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'ivDiffCutoffPercent', 'float', '5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'filterOptionWorth', 'boolean', 'TRUE');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'topOis', 'int', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 3, 'G3DualIVParityAndOIWorthStraddle-baseDelta0.5-ivDiffCutoffPercent5-filterOptionWorth-topOis5-noLimit', '09:20:45', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3DualIVParityAndOIWorthStraddleAlgoThread', 3, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'ivDiffCutoffPercent', 'float', '5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'filterOptionWorth', 'boolean', 'TRUE');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'topOis', 'int', '5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 2, 'G3GreekGap-greekGamma-baseDelta0.5-highLimit', '09:20:00', '15:15:00', 1, '1e+06', 100, -50, -10000, 10, 't', 't', 't', 't', 't', 'f', 'EXITED', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 33, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'gamma');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 3, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 45, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 5, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 53, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 7, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 53, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 8, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 53, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 9, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 53, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO "public"."nexcorio_options_algo_strategy" ("id", "f_user", "f_main_instrument", "algoname", "entry_time", "exit_time", "no_of_lots", "max_fund_allocated", "target", "stoploss", "trailing_stoploss", "max_allowed_nooforders", "order_enabled_monday", "order_enabled_tuesday", "order_enabled_wednesday", "order_enabled_thursday", "order_enabled_friday", "manual_exit_enabled", "status", "favourite", "isactive", "algo_class_name", "f_parent", "hedge_distance") VALUES (nextval('nexcorio_options_algo_strategy_id_seq'), 1, 10, 'G3GreekGap-greekIV-baseDelta0.5-noLimit', '09:20:00', '15:15:00', 1, '100000', 10000, -10000, -10000, 100, 'f', 'f', 'f', 'f', 'f', 'f', 'Exited', 'f', 't', 'com.nexcorio.algo.strategy.G3GreekGapAlgoThread', 53, 700);
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'greekname', 'String', 'iv');
INSERT INTO "public"."nexcorio_options_algo_strategy_parameters" ("id", "f_strategy", "name", "data_type", "value") VALUES (nextval('nexcorio_options_algo_strategy_parameters_id_seq'), (SELECT last_value FROM nexcorio_options_algo_strategy_id_seq), 'baseDelta', 'float', '0.5');

INSERT INTO db_versions VALUES('0011', now(), 'Keshav', 'Some initial algo stratgeies','Data' );
